Learing the basics of Neural Network

In [1]:
#Import all the necessary packages
import numpy as np
import math
import matplotlib.pyplot as plt
import cv2

### Receptive Field
$$y=b+\sum\limits_{x=1}^{n} {w*x}$$

The above problem is same as:
$$ y= mx +c$$

#### Example of using Neural Network 
$$x_{input}=[2,3,4,5,6,7,8,9,10]; x_{size}= 9x1$$

$$y_{obs}=[4,6,8,10,12,14,16,18,20]; y_{size}= 9x1$$

$$w= $$
\begin{bmatrix} 
w_{11} & w_{12} & w_{13} & w_{14} & w_{15} & w_{16} & w_{17} & w_{18} & w_{19}\\
w_{21} & w_{22} & w_{23} & w_{24} & w_{25} & w_{26} & w_{27} & w_{28} & w_{29}\\
w_{31} & w_{32} & w_{33} & w_{34} & w_{35} & w_{36} & w_{37} & w_{38} & w_{39}\\
w_{41} & w_{42} & w_{43} & w_{44} & w_{45} & w_{46} & w_{47} & w_{48} & w_{49}\\
w_{51} & w_{52} & w_{53} & w_{54} & w_{55} & w_{56} & w_{57} & w_{58} & w_{59}\\
w_{61} & w_{62} & w_{63} & w_{64} & w_{65} & w_{66} & w_{67} & w_{68} & w_{69}\\
w_{71} & w_{72} & w_{73} & w_{74} & w_{75} & w_{76} & w_{77} & w_{78} & w_{79}\\
w_{81} & w_{82} & w_{83} & w_{84} & w_{85} & w_{86} & w_{87} & w_{88} & w_{89}\\
w_{91} & w_{92} & w_{93} & w_{94} & w_{95} & w_{96} & w_{97} & w_{98} & w_{99}
\end{bmatrix}


Hence Receptive Field-
$$x^T.w=(1x9).(9x9)=(1x9)$$
$$w.x^T=(1x9).(9x9)=(1x9)$$

So solving using $$w.x^T=(1x9).(9x9)=(1x9)$$









In [21]:
#inputs
#x=np.array([2,3,4,5,6,7,8,9,10])
x=np.array([2,3,4])
x=np.transpose(x)
print x.size
#w=[1,2,2,2,2,2,2,2,2,2]
#w=np.random.uniform(0,1,(x.size,x.size))
#wsize=(x.size,x.size)
#w=np.ones(wsize)
#w=np.transpose(w)
#print w.shape
#print "Weights:",w
#y=[4,6,8,10,12,14,16,18,20]
y=[4,6,8]
#w=np.random.rand(4,4)
#w=np.full((3,3), 1)
w=np.ones((3,3), dtype=float)
print w
#receptive=[]
#error=[]

3
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [22]:
#Receptive field y=transpose(w)*x
def receptiveField(w,x):
    perNeuron=np.dot(w,x)
    #print perNeuron
    return perNeuron 

def activationFunc(receptive):
    #aplha=1
    #sigmoid=1/(1+np.exp(-np.dot(aplha,receptive)))
    sigmoid=receptive
    return sigmoid
    
def errorFunc(activation):
    error=activation-y
    #print error
    return error
    

In [23]:
receptive= receptiveField(w,x)
print "Receptive:", receptive 
#activation=activationFunc(receptive)  
#print "Activation:",activation
#yobs=errorFunc(activation)

print "Y:", y
error=errorFunc(receptive)
print "Error in Y observed-Y:",error

print "Weights before update:",w
#print "Updated Weights"
#update Weights
def updateWeight(w):
    LR=0.05
    for i in xrange(3):
        for j in xrange(3):
            w[j,i]=(w[j,i])-(LR*error[i]*x[i])
    print w

#updateWeight()
def checkError(error):
    for n in xrange(10):
        for i in xrange(3):
            if error[i] !=0:
                print "Updated Weights"
                print "", updateWeight(w)
                receptive= receptiveField(w,x)        
                print "Receptive:", receptive 
                error=errorFunc(receptive)
                print "Error in Y observed-Y:",error


checkError(error) 

#Check the change in error; delta error


Receptive: [9. 9. 9.]
Y: [4, 6, 8]
Error in Y observed-Y: [5. 3. 1.]
Weights before update: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Updated Weights
 [[0.5  0.55 0.8 ]
 [0.5  0.55 0.8 ]
 [0.5  0.55 0.8 ]]
None
Receptive: [5.85 5.85 5.85]
Error in Y observed-Y: [ 1.85 -0.15 -2.15]
Updated Weights
 [[0.  0.1 0.6]
 [0.  0.1 0.6]
 [0.  0.1 0.6]]
None
Receptive: [2.7 2.7 2.7]
Error in Y observed-Y: [-1.3 -3.3 -5.3]
Updated Weights
 [[-0.5  -0.35  0.4 ]
 [-0.5  -0.35  0.4 ]
 [-0.5  -0.35  0.4 ]]
None
Receptive: [-0.45 -0.45 -0.45]
Error in Y observed-Y: [-4.45 -6.45 -8.45]
Updated Weights
 [[-1.  -0.8  0.2]
 [-1.  -0.8  0.2]
 [-1.  -0.8  0.2]]
None
Receptive: [-3.6 -3.6 -3.6]
Error in Y observed-Y: [ -7.6  -9.6 -11.6]
Updated Weights
 [[-1.50000000e+00 -1.25000000e+00  5.55111512e-17]
 [-1.50000000e+00 -1.25000000e+00  5.55111512e-17]
 [-1.50000000e+00 -1.25000000e+00  5.55111512e-17]]
None
Receptive: [-6.75 -6.75 -6.75]
Error in Y observed-Y: [-10.75 -12.75 -14.75]
Updated Weights
 [[-2.  -1.7 

In [20]:
receptive= receptiveField(w,x)
print "Receptive:", receptive 
error=errorFunc(receptive)
print "Error in Y observed-Y:",error



Receptive: [-0.45 -0.45 -0.45]
Error in Y observed-Y: [-4.45 -6.45 -8.45]


In [ ]:
#receptiveField=np.dot(w,x)
#print receptiveField
#error=y-receptiveField
#print error
    
def update(w):
    LR=1.5
    print "Hello"
    receptiveField=np.dot(w,x)
    error=y-receptiveField    
    while (abs((error.) == 0.0 ):
        print "Hello While"
        w=w-(LR*error)
        receptiveField=np.dot(w,x)
        error=y-receptiveField
        print error
        #update(w,error)
    return w    

Image as an Input

In [163]:
# read image into matrix.
m =  cv2.imread("Y2x.png")

In [167]:
# get image properties.
h,w,bpp = np.shape(m)
print "h:",h
print "w:",w
print "bpp:",bpp

print np.shape(m)
# print pixel value
y = 1
x = 1
print m[y][x]

h: 252
w: 382
bpp: 3
(252, 382, 3)
[255 255 255]
